version: "3.8"

networks:
  ergo-node:
    external: true

services:
  # Postgresql database
  db:
    build:
      context: ./watcher/db
    environment:
      POSTGRES_DB: ergo
      POSTGRES_USER: ergo
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./watcher/db/db.secret
    volumes:
      - /var/lib/ergowatch_pg/14/data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # Watcher
  watcher:
    build:
      context: ./watcher
    volumes:
      - ./watcher/docker.toml:/ew/config.toml:ro
    links:
      - "db"
    networks:
      - default
      - ergo-node
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
 
  # API server
  api:
    build:
      context: ./api
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ergo
      POSTGRES_USER: ergo
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./watcher/db/db.secret
    links:
      - "db"
    ports:
      - "127.0.0.1:8001:80"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
